### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by hugofabricio** [Lykegenes/laravel-datagrid-builder#11]
How to define buttons edit, create and view?

**Comment by patricksamson** [comment]
Here's an example below.

But honestly, trying to build dynamic tables directly in Laravel quickly becomes a nightmare.
Here's why : 
- You won't save that much time (compared to a Blade view)
- It is much less flexible than a Blade view
- It is hard to maintain and modify
- It adds yet another level of complexity
- You'll probably need Javascript anyway

Personally, I'd give a shot to [Vue.js](http://vuejs.org/), along with [Bootstrap-table](https://github.com/wenzhixin/bootstrap-table) or a custom Vue.js dynamic table component. That would give you a much better control of what's happening client-side, as well as separating your front end from your back end (front end makes API calls to back end).

Anyway, just my opinion :+1: 

``` php
<?php

namespace App\Datagrids;

use Lykegenes\DatagridBuilder\Datagrid;

class PeopleDatagrid extends Datagrid
{
    public function buildDatagrid()
    {
        $this->add('firstName')
             ->add('lastName')
             ->add('email')

             // This adds the column
             ->add('actions', [
                 'attr' => [
                    // Display the output from a formatter (Javascript code running client-side).
                    // For details, see https://github.com/Lykegenes/laravel-datagrid-builder/blob/master/views/formatters/default.blade.php
                    'data-formatter' => 'DatagridBuilder.actions',
                ],
             ])

             // Add the urls that the buttons will link to
             ->addData(['formatters.actions.view' => '#']);
             ->addData(['formatters.actions.edit' => '#']);
             ->addData(['formatters.actions.delete' => '#']);
    }
}
```
